#!/usr/bin/env bash

# Advanced Forensic Web Capture Tool with Digital Signatures
# Creates court-admissible web page captures with cryptographic proof

set -euo pipefail

# Configuration
MODE="${1:-capture}"
OUTPUT_DIR="${2:-}"
URL="${3:-}"
WITNESS="${4:-$USER}"

show_usage() {
    cat <<EOF
Forensic Web Capture Tool with Cryptographic Signatures

Usage:
  $0 capture [output_dir] <URL> [witness_name]  - Capture and sign
  $0 verify <capture_dir>                        - Verify signatures
  $0 report <capture_dir>                        - Generate court report

Features:
  - Timestamped capture with NTP verification
  - SHA256 and SHA512 hashes
  - GPG digital signatures
  - Complete page preservation
  - Chain of custody with cryptographic proof
  - Tamper detection
EOF
    exit 1
}

# Verify mode
if [ "$MODE" = "verify" ]; then
    CAPTURE_DIR="$OUTPUT_DIR"
    if [ -z "$CAPTURE_DIR" ] || [ ! -d "$CAPTURE_DIR" ]; then
        echo "Error: Please specify a valid capture directory to verify"
        show_usage
    fi
    
    echo "=== FORENSIC CAPTURE VERIFICATION ==="
    echo "Directory: $CAPTURE_DIR"
    echo "Verification Time: $(date -Iseconds)"
    echo "======================================"
    
    # Check SHA256 hashes
    echo "[1/3] Verifying SHA256 hashes..."
    if cd "$CAPTURE_DIR" && sha256sum -c SHA256SUMS.txt; then
        echo "✓ SHA256 verification PASSED"
    else
        echo "✗ SHA256 verification FAILED - Files have been modified!"
        exit 1
    fi
    
    # Check SHA512 hashes if available
    if [ -f "$CAPTURE_DIR/SHA512SUMS.txt" ]; then
        echo "[2/3] Verifying SHA512 hashes..."
        if cd "$CAPTURE_DIR" && sha512sum -c SHA512SUMS.txt; then
            echo "✓ SHA512 verification PASSED"
        else
            echo "✗ SHA512 verification FAILED"
            exit 1
        fi
    fi
    
    # Verify GPG signature if available
    if [ -f "$CAPTURE_DIR/SHA256SUMS.txt.sig" ]; then
        echo "[3/3] Verifying GPG signature..."
        if gpg --verify "$CAPTURE_DIR/SHA256SUMS.txt.sig" "$CAPTURE_DIR/SHA256SUMS.txt" 2>&1; then
            echo "✓ GPG signature verification PASSED"
        else
            echo "⚠ GPG signature verification failed or key not available"
        fi
    else
        echo "⚠ No GPG signature found"
    fi
    
    echo ""
    echo "=== VERIFICATION COMPLETE ==="
    echo "Result: INTEGRITY VERIFIED ✓"
    exit 0
fi

# Report mode
if [ "$MODE" = "report" ]; then
    CAPTURE_DIR="$OUTPUT_DIR"
    if [ -z "$CAPTURE_DIR" ] || [ ! -d "$CAPTURE_DIR" ]; then
        echo "Error: Please specify a valid capture directory"
        show_usage
    fi
    
    REPORT_FILE="$CAPTURE_DIR/forensic_report_$(date +%Y%m%d_%H%M%S).pdf"
    
    cat > "$CAPTURE_DIR/forensic_report.md" <<EOF
# FORENSIC WEB CAPTURE REPORT

## Executive Summary
This report documents the forensic capture of web content for legal purposes.

## Capture Details
$(cat "$CAPTURE_DIR/capture_metadata.txt")

## File Inventory
\`\`\`
$(ls -la "$CAPTURE_DIR")
\`\`\`

## Integrity Verification

### SHA256 Hashes
\`\`\`
$(head -20 "$CAPTURE_DIR/SHA256SUMS.txt")
... (truncated, see SHA256SUMS.txt for full list)
\`\`\`

### Verification Status
$(cd "$CAPTURE_DIR" && sha256sum -c SHA256SUMS.txt 2>&1 | tail -5)

## Chain of Custody
$(cat "$CAPTURE_DIR/chain_of_custody.txt")

## Declaration
I certify that this report accurately represents the forensic capture
performed and that all integrity checks have been verified.

Date: $(date -Iseconds)
Prepared by: $USER

---
*This report was automatically generated by the Forensic Web Capture Tool*
EOF

    # Convert to PDF if pandoc is available
    if command -v pandoc &> /dev/null; then
        pandoc "$CAPTURE_DIR/forensic_report.md" -o "$REPORT_FILE" 2>/dev/null && \
        echo "Report generated: $REPORT_FILE" || \
        echo "Markdown report generated: $CAPTURE_DIR/forensic_report.md"
    else
        echo "Report generated: $CAPTURE_DIR/forensic_report.md"
        echo "(Install pandoc to generate PDF reports)"
    fi
    exit 0
fi

# Capture mode
if [ "$MODE" != "capture" ]; then
    show_usage
fi

if [ -z "$URL" ]; then
    OUTPUT_DIR=""
    URL="$2"
    WITNESS="$3"
fi

if [ -z "$URL" ]; then
    show_usage
fi

if [ -z "$OUTPUT_DIR" ]; then
    OUTPUT_DIR="./capture_$(date +%Y%m%d_%H%M%S)"
fi

echo "=== FORENSIC WEB CAPTURE WITH SIGNATURES ==="
echo "Date/Time: $(date -Iseconds)"
echo "URL: $URL"
echo "Witness: $WITNESS"
echo "Output: $OUTPUT_DIR"
echo "==========================================="

# Check for GPG
GPG_AVAILABLE=false
if command -v gpg &> /dev/null; then
    GPG_KEY=$(gpg --list-secret-keys --keyid-format LONG 2>/dev/null | grep sec | head -1 | awk '{print $2}' | cut -d'/' -f2)
    if [ -n "$GPG_KEY" ]; then
        GPG_AVAILABLE=true
        echo "GPG Key found: $GPG_KEY"
    else
        echo "⚠ No GPG key found - signatures will not be created"
        echo "  To create a key: gpg --gen-key"
    fi
fi

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Try to get network time for accuracy
echo "Synchronizing time..."
if command -v ntpdate &> /dev/null; then
    sudo ntpdate -q pool.ntp.org > "$OUTPUT_DIR/ntp_time.txt" 2>&1 || true
fi

# Create detailed metadata file
cat > "$OUTPUT_DIR/capture_metadata.txt" <<EOF
FORENSIC WEB CAPTURE METADATA
==============================
Capture ID: $(uuidgen 2>/dev/null || echo "$(date +%s)-$$")
Capture Date/Time (UTC): $(date -u -Iseconds)
Capture Date/Time (Local): $(date -Iseconds)
Timezone: $(date +%Z)
UNIX Timestamp: $(date +%s)
Target URL: $URL
Domain: $(echo "$URL" | sed -e 's|^[^/]*//||' -e 's|/.*$||')
Witness/Operator: $WITNESS
System: $(uname -a)
Hostname: $(hostname -f)
IP Address: $(ip addr show | grep 'inet ' | grep -v '127.0.0.1' | head -1 | awk '{print $2}')
Network Route to Target: 
$(traceroute -n -m 5 $(echo "$URL" | sed -e 's|^[^/]*//||' -e 's|/.*$||') 2>/dev/null | head -6 || echo "traceroute not available")
==============================
EOF

# DNS lookup
echo "Resolving DNS..."
echo "DNS Resolution:" >> "$OUTPUT_DIR/capture_metadata.txt"
host $(echo "$URL" | sed -e 's|^[^/]*//||' -e 's|/.*$||') >> "$OUTPUT_DIR/capture_metadata.txt" 2>&1 || true
echo "==============================" >> "$OUTPUT_DIR/capture_metadata.txt"

# 1. Capture with wget
echo "[1/7] Capturing complete page with wget..."
wget \
    --page-requisites \
    --convert-links \
    --adjust-extension \
    --no-parent \
    --timestamping \
    --no-cookies \
    --span-hosts \
    --backup-converted \
    --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (Forensic Capture)" \
    --directory-prefix="$OUTPUT_DIR/wget_capture" \
    --output-file="$OUTPUT_DIR/wget.log" \
    "$URL"

# 2. Capture raw HTML with curl (with headers)
echo "[2/7] Capturing raw HTML and headers..."
curl -H "User-Agent: Mozilla/5.0 (Forensic Capture)" \
     -i \
     -L \
     --trace-ascii "$OUTPUT_DIR/curl_trace.txt" \
     --trace-time \
     "$URL" > "$OUTPUT_DIR/raw_response.txt" 2> "$OUTPUT_DIR/curl.log"

# 3. Capture HTTP headers separately
echo "[3/7] Capturing HTTP headers..."
curl -I -L "$URL" > "$OUTPUT_DIR/http_headers.txt" 2>&1

# 4. Take screenshot
echo "[4/7] Attempting screenshot capture..."
if command -v wkhtmltoimage &> /dev/null; then
    wkhtmltoimage \
        --width 1920 \
        --height 0 \
        --javascript-delay 5000 \
        --quality 100 \
        "$URL" \
        "$OUTPUT_DIR/screenshot_$(date +%Y%m%d_%H%M%S).png" 2> "$OUTPUT_DIR/screenshot.log" || \
    echo "Screenshot failed, trying alternative method..."
fi

# Alternative screenshot with chromium if available
if command -v chromium &> /dev/null; then
    chromium --headless --disable-gpu --screenshot="$OUTPUT_DIR/screenshot_chromium.png" \
             --window-size=1920,1080 "$URL" 2>/dev/null || true
fi

# 5. Capture as PDF
echo "[5/7] Attempting PDF capture..."
if command -v wkhtmltopdf &> /dev/null; then
    wkhtmltopdf \
        --enable-javascript \
        --javascript-delay 5000 \
        --print-media-type \
        "$URL" \
        "$OUTPUT_DIR/page_$(date +%Y%m%d_%H%M%S).pdf" 2> "$OUTPUT_DIR/pdf.log" || true
fi

# 6. Generate both SHA256 and SHA512 hashes
echo "[6/7] Generating cryptographic hashes..."
find "$OUTPUT_DIR" -type f ! -name "*.sig" -exec sha256sum {} \; > "$OUTPUT_DIR/SHA256SUMS.txt"
find "$OUTPUT_DIR" -type f ! -name "*.sig" -exec sha512sum {} \; > "$OUTPUT_DIR/SHA512SUMS.txt"

# 7. Create GPG signatures if available
if [ "$GPG_AVAILABLE" = true ]; then
    echo "[7/7] Creating digital signatures..."
    gpg --detach-sign --armor "$OUTPUT_DIR/SHA256SUMS.txt"
    gpg --detach-sign --armor "$OUTPUT_DIR/capture_metadata.txt"
    echo "Digital signatures created with key: $GPG_KEY"
else
    echo "[7/7] Skipping digital signatures (no GPG key)"
fi

# Create chain of custody document
cat > "$OUTPUT_DIR/chain_of_custody.txt" <<EOF
DIGITAL CHAIN OF CUSTODY RECORD
================================
Case/Matter: [TO BE FILLED]
Evidence ID: $(uuidgen 2>/dev/null || echo "$(date +%s)-$$")

Initial Capture
---------------
Date/Time: $(date -Iseconds)
Performed by: $WITNESS
Method: Forensic Web Capture Tool v1.0
Digital Signature: $([ "$GPG_AVAILABLE" = true ] && echo "Yes (GPG Key: $GPG_KEY)" || echo "No")

Target Information
------------------
URL: $URL
IP Resolution: $(dig +short $(echo "$URL" | sed -e 's|^[^/]*//||' -e 's|/.*$||') | head -1)

Capture Methods Used
--------------------
✓ Complete page download (wget)
✓ Raw HTTP response (curl)
✓ HTTP headers
$([ -f "$OUTPUT_DIR/screenshot_"*.png ] && echo "✓ Screenshot capture" || echo "○ Screenshot capture (failed)")
$([ -f "$OUTPUT_DIR/page_"*.pdf ] && echo "✓ PDF rendering" || echo "○ PDF rendering (failed)")

Files Created
-------------
Total files: $(find "$OUTPUT_DIR" -type f | wc -l)
Total size: $(du -sh "$OUTPUT_DIR" | cut -f1)

Integrity Measures
------------------
SHA256 Hash: $(sha256sum "$OUTPUT_DIR/capture_metadata.txt" | cut -d' ' -f1)
SHA512 Hash: $(sha512sum "$OUTPUT_DIR/capture_metadata.txt" | cut -d' ' -f1)
GPG Signed: $([ "$GPG_AVAILABLE" = true ] && echo "Yes" || echo "No")

Verification Instructions
-------------------------
1. To verify file integrity:
   cd "$OUTPUT_DIR" && sha256sum -c SHA256SUMS.txt

2. To verify signatures (if signed):
   gpg --verify SHA256SUMS.txt.sig SHA256SUMS.txt

3. To generate court report:
   forensic-webcapture report "$OUTPUT_DIR"

DECLARATION
-----------
I, the undersigned, certify that:
1. This capture was performed on the date and time specified above
2. The captured content accurately represents the target URL at that time
3. No alterations have been made to the captured content
4. The cryptographic hashes provide proof of integrity

_______________________        _______________________
Signature of Witness           Date

_______________________
Printed Name: $WITNESS
EOF

# Create verification script
cat > "$OUTPUT_DIR/verify.sh" <<'VERIF'
#!/bin/bash
echo "=== FORENSIC CAPTURE VERIFICATION ==="
PASS=true

echo "Checking SHA256 integrity..."
if sha256sum -c SHA256SUMS.txt >/dev/null 2>&1; then
    echo "✓ SHA256 verification PASSED"
else
    echo "✗ SHA256 verification FAILED"
    PASS=false
fi

if [ -f SHA512SUMS.txt ]; then
    echo "Checking SHA512 integrity..."
    if sha512sum -c SHA512SUMS.txt >/dev/null 2>&1; then
        echo "✓ SHA512 verification PASSED"
    else
        echo "✗ SHA512 verification FAILED"
        PASS=false
    fi
fi

if [ -f SHA256SUMS.txt.sig ]; then
    echo "Checking GPG signature..."
    if gpg --verify SHA256SUMS.txt.sig SHA256SUMS.txt 2>/dev/null; then
        echo "✓ GPG signature VALID"
    else
        echo "⚠ GPG signature check failed (key may not be available)"
    fi
fi

if [ "$PASS" = true ]; then
    echo ""
    echo "=== VERIFICATION COMPLETE: INTEGRITY CONFIRMED ==="
else
    echo ""
    echo "=== VERIFICATION FAILED: FILES MAY BE TAMPERED ==="
    exit 1
fi
VERIF
chmod +x "$OUTPUT_DIR/verify.sh"

# Final summary
echo "==========================================="
echo "CAPTURE COMPLETE!"
echo ""
echo "Output directory: $OUTPUT_DIR"
echo "Files captured: $(find "$OUTPUT_DIR" -type f | wc -l)"
echo "Total size: $(du -sh "$OUTPUT_DIR" | cut -f1)"
echo ""
if [ "$GPG_AVAILABLE" = true ]; then
    echo "✓ Digitally signed with GPG key: $GPG_KEY"
else
    echo "⚠ Not digitally signed (configure GPG for signatures)"
fi
echo ""
echo "Next steps:"
echo "1. Verify integrity: cd $OUTPUT_DIR && ./verify.sh"
echo "2. Generate report: forensic-webcapture report $OUTPUT_DIR"
echo "3. For court: Print and sign chain_of_custody.txt"
echo ""
echo "IMPORTANT: Do not modify any files in the capture directory!"