"""
Hyprland Monitor Setup Tool
Automatically configures monitor layouts based on connected displays.
"""

import json
import subprocess
import sys
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import List


class MonitorType(Enum):
    PHILIPS_4K = "philips_4k"
    GIGABYTE_4K = "gigabyte_4k"
    DELL_4K = "dell_4k"
    PHILIPS_2560X1600 = "philips_2560x1600"
    TRAVEL_RTK = "travel_rtk"
    GENERIC = "generic"


@dataclass
class Monitor:
    name: str
    description: str
    width: int
    height: int
    monitor_type: MonitorType

    @property
    def resolution(self) -> str:
        return f"{self.width}x{self.height}"


class HyprlandMonitorSetup:
    LAPTOP_MONITOR = "eDP-1"
    LAPTOP_RESOLUTION = "1920x1200@60"

    MONITORS_CONF = Path.home() / ".config/hypr/monitors.conf"
    MONITORS_LUA = Path.home() / ".config/hypr/monitors.lua"

    def __init__(self):
        self.monitors: List[Monitor] = []
        self.externals: List[Monitor] = []
        self._pending_configs: List[str] = []

    def get_monitors(self) -> List[Monitor]:
        """Get connected monitors from hyprctl."""
        try:
            result = subprocess.run(
                ["hyprctl", "monitors", "-j"],
                capture_output=True,
                text=True,
                check=True
            )
            monitors_data = json.loads(result.stdout)

            monitors = []
            for monitor_data in monitors_data:
                monitor_type = self._detect_monitor_type(monitor_data["description"])
                monitor = Monitor(
                    name=monitor_data["name"],
                    description=monitor_data["description"],
                    width=monitor_data["width"],
                    height=monitor_data["height"],
                    monitor_type=monitor_type
                )
                monitors.append(monitor)

            return monitors

        except (subprocess.CalledProcessError, json.JSONDecodeError) as e:
            print(f"Error getting monitor information: {e}")
            sys.exit(1)

    def _detect_monitor_type(self, description: str) -> MonitorType:
        """Detect monitor type based on description."""
        if "PHL 276E8V" in description:
            return MonitorType.PHILIPS_4K
        elif "M28U" in description:
            return MonitorType.GIGABYTE_4K
        elif "DELL P2723QE" in description or "Dell" in description:
            return MonitorType.DELL_4K
        elif "PHL 276E1" in description:
            return MonitorType.PHILIPS_2560X1600
        elif "RTK Monitor" in description:
            return MonitorType.TRAVEL_RTK
        else:
            return MonitorType.GENERIC

    def apply_config(self, config: str) -> None:
        """Queue a monitor configuration."""
        print(f"  monitor={config}")
        self._pending_configs.append(config)

    @staticmethod
    def _lua_monitor(config: str) -> str:
        """Convert 'output,mode,position,scale' into an hl.monitor() call."""
        output, mode, position, scale = config.rsplit(",", 3)

        def lit(value: str) -> str:
            try:
                return repr(float(value) if "." in value else int(value))
            except ValueError:
                return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')

        return (
            "hl.monitor({ output = %s, mode = %s, position = %s, scale = %s })"
            % (lit(output), lit(mode), lit(position), lit(scale))
        )

    def flush_configs(self) -> bool:
        """Write queued configs and reload Hyprland. Returns True if the
        layout changed; unchanged layouts skip the write and reload so
        hotplug event bursts don't flap waybar and the compositor."""
        if not self._pending_configs:
            return False
        configs = self._pending_configs + [",preferred,auto,1"]

        lines = [f"monitor={c}" for c in configs]
        conf_text = "\n".join(lines) + "\n"

        # Hyprland 0.56+ reads hyprland.lua, which cannot source a .conf file,
        # so emit the same layout as hl.monitor() calls.
        lua = ["-- AUTOGENERATED by ~/.config/hypr/monitor-setup.py. Do not edit."]
        lua += [self._lua_monitor(c) for c in configs]
        lua_text = "\n".join(lua) + "\n"

        self._pending_configs = []
        try:
            unchanged = (
                self.MONITORS_CONF.read_text() == conf_text
                and self.MONITORS_LUA.read_text() == lua_text
            )
        except OSError:
            unchanged = False
        if unchanged:
            print("Layout unchanged, skipping reload")
            return False

        self.MONITORS_CONF.write_text(conf_text)
        print(f"Wrote {self.MONITORS_CONF}")
        self.MONITORS_LUA.write_text(lua_text)
        print(f"Wrote {self.MONITORS_LUA}")
        subprocess.run(["hyprctl", "reload"], check=True)
        return True

    def setup_single_monitor(self) -> None:
        """Configure laptop-only mode."""
        print("Laptop only mode")
        self.apply_config(f"{self.LAPTOP_MONITOR},{self.LAPTOP_RESOLUTION},0x0,1")

    def setup_dual_monitor(self) -> None:
        """Configure dual monitor setup."""
        print("Dual monitor setup")
        external = self.externals[0]

        # Hyprland anchors eDP-1 at 0,0 and ignores position rules for it, so
        # the external goes at a negative offset (left of the laptop).
        if external.monitor_type in [MonitorType.GIGABYTE_4K, MonitorType.DELL_4K] or external.width == 3840:
            # 4K monitor no scaling
            self.apply_config(f"{external.name},3840x2160@60,-3840x0,1")
        else:
            self.apply_config(f"{external.name},preferred,-{external.width}x0,1")
        self.apply_config(f"{self.LAPTOP_MONITOR},{self.LAPTOP_RESOLUTION},0x0,1")

    def setup_triple_monitor_mobile(self) -> None:
        """Configure mobile setup with two 2560x1600 monitors stacked, right of laptop."""
        print("Mobile setup: Two 2560x1600 monitors - applying stacked layout right of laptop")

        # Match panels by description (which embeds the EDID serial). The
        # native panels report serial 0x01010100; one of them is overridden
        # at the kernel level to report 0x02010100 (see configuration.nix
        # hardware.display.outputs). DP connector names are unstable across
        # reboots, so name-based matching does not survive.
        rtk_orig = "desc:Invalid Vendor Codename - RTK Monitor 0x01010100"
        rtk_mod = "desc:Invalid Vendor Codename - RTK Monitor 0x02010100"
        external_height = 1600
        laptop_width = 1920
        # Two externals stacked vertically on the right (rtk_orig top, rtk_mod
        # bottom), laptop to their left at 0,0 (Hyprland anchors eDP-1 there),
        # top-aligned with the top panel.
        self.apply_config(f"{self.LAPTOP_MONITOR},{self.LAPTOP_RESOLUTION},0x0,1")
        self.apply_config(f"{rtk_orig},2560x1600@60,{laptop_width}x0,1")
        self.apply_config(f"{rtk_mod},2560x1600@60,{laptop_width}x{external_height},1")

    def setup_triple_monitor_office(self, mon1: Monitor, mon2: Monitor) -> None:
        """Configure office setup with two 4K monitors in horizontal layout."""
        print("Office setup: Two 4K monitors - applying horizontal layout")

        # Determine which is which (Gigabyte left, Philips center)
        if mon1.monitor_type == MonitorType.GIGABYTE_4K:
            left_mon, center_mon = mon1, mon2
        else:
            left_mon, center_mon = mon2, mon1

        # Laptop at origin (Hyprland anchors eDP-1 at 0,0)
        self.apply_config(f"{self.LAPTOP_MONITOR},{self.LAPTOP_RESOLUTION},0x0,1")
        # Left monitor (Gigabyte 4K) - far left
        self.apply_config(f"{left_mon.name},3840x2160@60,-7680x0,1")
        # Center monitor (Philips 4K) - between Gigabyte and laptop
        self.apply_config(f"{center_mon.name},3840x2160@60,-3840x0,1")

    def setup_triple_monitor_generic(self) -> None:
        """Configure generic triple monitor setup with horizontal layout."""
        print("Generic triple monitor setup - applying horizontal layout")

        x_offset = 0
        for monitor in self.externals:
            self.apply_config(f"{monitor.name},{monitor.resolution}@60,{x_offset}x0,1")
            x_offset += monitor.width

        self.apply_config(f"{self.LAPTOP_MONITOR},{self.LAPTOP_RESOLUTION},{x_offset}x0,1")

    def setup_triple_monitor(self) -> None:
        """Configure triple monitor setup based on detected monitor types."""
        print("Triple monitor setup detected")

        mon1, mon2 = self.externals[0], self.externals[1]

        # Check for mobile setup: a pair of travel/portable 2560x1600 panels.
        mobile_types = {MonitorType.PHILIPS_2560X1600, MonitorType.TRAVEL_RTK}
        mobile_condition = (
            mon1.monitor_type in mobile_types
            and mon2.monitor_type in mobile_types
            and mon1.monitor_type == mon2.monitor_type
        )

        if mobile_condition:
            self.setup_triple_monitor_mobile()
            return

        # Check for office setup (two 4K monitors)
        office_condition = (
            (mon1.monitor_type == MonitorType.PHILIPS_4K and
             mon2.monitor_type == MonitorType.GIGABYTE_4K) or
            (mon1.monitor_type == MonitorType.GIGABYTE_4K and
             mon2.monitor_type == MonitorType.PHILIPS_4K)
        )

        if office_condition:
            self.setup_triple_monitor_office(mon1, mon2)
            return

        # Default to generic setup
        self.setup_triple_monitor_generic()

    def run(self) -> None:
        """Main entry point for monitor setup."""
        self.monitors = self.get_monitors()
        self.externals = [m for m in self.monitors if m.name != self.LAPTOP_MONITOR]

        monitor_count = len(self.monitors)
        print(f"Detected {monitor_count} monitors")

        if monitor_count == 1:
            self.setup_single_monitor()
        elif monitor_count == 2:
            self.setup_dual_monitor()
        elif monitor_count == 3:
            self.setup_triple_monitor()
        else:
            print(f"Unsupported monitor count: {monitor_count}")
            sys.exit(1)

        changed = self.flush_configs()
        print("Monitor configuration applied")

        # Restart Waybar only when the layout actually changed
        if changed:
            subprocess.Popen(
                [str(Path.home() / ".config/hypr/restart-waybar.sh")],
                start_new_session=True
            )


def main():
    """Main function."""
    try:
        setup = HyprlandMonitorSetup()
        setup.run()
    except KeyboardInterrupt:
        print("\nSetup interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
