# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [
      #<nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/c877856a-b1e1-4b1a-be1e-980f8187745b";
      fsType = "f2fs";
    };
  /*
    fileSystems."/home/" = {
    device = "/dev/disk/by-uuid/159273dd-3f19-4645-b8bd-6416fee6008e";
    fsType = "ext4";
    	mountPoint = "/home/";
    };
  */

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/159273dd-3f19-4645-b8bd-6416fee6008e";
    fsType = "ext4";
    mountPoint = "/mnt/data";
  };

  fileSystems."/home" = {
    device = "/mnt/data/home";
    options = [ "bind" ];
  };

  fileSystems."/tmp" = {
    device = "/mnt/data/tmp";
    options = [ "bind" ];
  };

  #fileSystems."/var" = {
  #      device = "/mnt/data/var";
  #      options = [ "bind" ];
  #};


  swapDevices = [ ];

  nix.settings.max-jobs = lib.mkDefault 12;
}
