name: "PR Describer"
on:
  pull_request:
jobs:
  describe:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: jester
          - target: alicia
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Nix derivation diff
      id: nix_diff
      run: nix store diff-closures github:${{ GITHUB_ACTION_REPOSITORY }}/${{ GITHUB_BASE_REF }}#nixosConfigurations.${{ matrix.target }}.config.system.build.toplevel .#nixosConfiguration.${{ matrix.target }}.config.system.build.toplevel >> "$GITHUB_OUTPUT"

    - name: Comment report in pr
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "{{ matrix.target }}"
          message: |
            ### Report for `${{ matrix.target }}`
            <details>
            <summary> Version changes </summary> <br>
            <pre> ${{ steps.nix_diff.outputs }} </pre>
            </details>
